name: amma-streamlit
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    # App
    - streamlit
    # Data
    - pandas
    # Code Quality
    - pylint
    # Experiments
    - jupyterlab
    # ML
    - tensorflow
    - scikit-learn
    # Visualization
    - mlxtend
    - matplotlib
    # Pip packages
    - pip
    - pip:
          - peewee
