name: amma-streamlit
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.11
    # App
    - streamlit
    # Data
    - pandas
    # Code Quality
    - pylint
    # Experiments
    - jupyterlab
    # ML
    - scikit-learn=1.6.1
    # Visualization
    - mlxtend
    - matplotlib
    # Pip packages
    - pip
    - pip:
        # ORM
        - peewee
        # ML
        - tensorflow[and-cuda]==2.18.0
