name: ml-streamlit
channels:
  - defaults
dependencies:
  - python=3.12.8
  # App
  - streamlit
  # Data
  - pandas
  # Code Quality
  - pylint
  # Experiments
  - jupyterlab
  # Pip packages
  - pip
  - pip:
      - peewee
